set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf \; display-message "Reloaded!"

set -g mouse on               

set -g base-index 1           
setw -g pane-base-index 1     
setw -g mode-keys vi          

bind | split-window -h       
bind - split-window -v       
unbind '"'
unbind %

unbind-key Left
unbind-key Right
unbind-key Up
unbind-key Down

bind-key Left previous-window
bind-key Right next-window
bind-key Up select-window -t 1
bind-key Down select-window -t last

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n C-Left resize-pane -L 5
bind -n C-Right resize-pane -R 5
bind -n C-Up resize-pane -U 5
bind -n C-Down resize-pane -D 5

set-option -g status-bg black
set-option -g status-fg white
set-option -g status-left "#[fg=green] #S #[default]"
set-option -g status-right "#[fg=cyan]%H:%M %d-%b-%Y #[default]"

set-option -g display-panes-time 1000
set-option -g display-panes-active-colour cyan
set-option -g display-panes-colour blue

set -g history-limit 50000  
set -g detach-on-destroy off

bind -T copy-mode-vi v send-keys -X begin-selection   # Start selection with 'v'
bind -T copy-mode-vi y send-keys -X copy-selection    # Copy with 'y'
bind p paste-buffer                                    

bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"

bind S command-prompt -p "Save session as:" "run 'tmux save-session -t #S ~/tmux_sessions/#S'"
bind L command-prompt -p "Load session:" "run 'tmux load-session ~/tmux_sessions/#S'"

setw -g automatic-rename on
set -g automatic-rename-format "#W"

set -g terminal-overrides "xterm*:smcup@:rmcup@"  
set -g allow-rename off 
