set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

set -g mouse on

set -g set-titles on
set -g set-titles-string "#T"

setw -g mode-keys vi

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %


bind r source-file ~/.tmux.conf \; display-message "Reloaded!"

set-option -g status-bg black
set-option -g status-fg white
set-option -g status-left "#[fg=green]#S #[default]"
set-option -g status-right "#[fg=cyan]%H:%M %d-%b-%Y#[default]"


set -g base-index 1
setw -g pane-base-index 1
